[package]
name = "just-rust"
version = "0.1.0"
edition = "2024"
description = ""
default-run = "just-rust"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
strum = "0.27.2"
strum_macros = "0.27.2"
